### ISSUE TITLE
Inconsistent test reporting with Retries on Report Portal

### ISSUE THREAD

**Issue by ralfsman11** [nvborisenko/reportportal-extensions-ci#7]
Describe the Bug:
I am experiencing an issue with the merging of tests on Report Portal. The reporting is inconsistent—sometimes only the reruns appear, sometimes tests are duplicated, and sometimes the duplicates are the reruns while the first test is the initial run. It appears that the same tests are consistently reported incorrectly. Furthermore, when I run only the tests that exhibit this issue, the retries work correctly. Azure DevOps pipeline logs show that the tests ran 3 times. Is there a way for me to debug the issue, to understand where the issue is coming from more precisely?

Below I've added an exception we got in our API service, which might be related to our issue.

Expected Behaviour:
All failed tests should show up with 3 retries on ReportPortal without any duplicates.

Actual Behaviour:
Report portal shows some tests without retries, some duplicated and some with the incorrect number of retries

Versions :
MSTest NuGet 3.8.0
ReportPortal: 24.2
ReportPortal.Reqnroll NuGet: 1.2
ReportPortal.Client NuGet: 3.10.0
ReportPortal.Shared NuGet: 3.10.0
ReportPortal.Extensions.CI Nuget: 0.5.0
Reqnroll NuGet: 2.3.0

   ReportPortal service versions :
   ![Image](https://github.com/user-attachments/assets/abedb760-c90d-4904-9f97-dc11f7d43ef0)

Our Azure DevOps Pipeline task 
```
  - task: VsTest@3
    displayName: Run Tests
    inputs:
      testSelector: 'testAssemblies' # Select tests using test assemblies
      testAssemblyVer2: | # Path to your test assemblies
         **\Common.Automation\**\Common.Automation.dll
         **\Rulla.Automation\**\Rulla.Automation.dll
         **\VRF.Automation\**\VRF.Automation.dll
         **\IMF.Automation\**\IMF.Automation.dll
         !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)' # Folder to search for test assemblies
      runSettingsFile: 'Common.Automation/Settings/FunctionalChromePC.runsettings' # Path to your .runsettings file
      rerunFailedTests: true # Enable retry for failed tests
      rerunType: 'basedOnTestFailureCount' # Retry based on the number of failed tests
      rerunFailedTestCasesMaxLimit: '100'
      rerunMaxAttempts: '2' # Maximum number of retry attempts
      platform: '$(BuildPlatform)' # Specify the build platform (e.g., x64)
      configuration: '$(BuildConfiguration)' # Specify the build configuration (e.g., Release)
      diagnosticsEnabled: true # Enable diagnostics for troubleshooting
      resultsFolder: '$(System.DefaultWorkingDirectory)\TestResults'
      runTestsInIsolation: true  # Run each test in an isolated process
      uiTests: true
      # rerunType: 'basedOnTestFailurePercentage'
      # rerunFailedThreshold: '50' # Retry only if failure rate is below 50%
```
Additional Info: 
Our Report Portal API service showed this exception, could be unrelated but in case its not, im adding it here

```
2025-02-12 15:22:00.545 ERROR 1 --- [nio-8585-exec-2] c.e.r.r.c.e.rest.DefaultErrorResolver    : Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from item_attribute where id=?; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from item_attribute where id=?
 
org.springframework.orm.ObjectOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from item_attribute where id=?; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from item_attribute where id=?
```
Screenshots:

Example #1:

![Image](https://github.com/user-attachments/assets/2d4ef2d8-e86b-4844-b502-a601bf12dc25)
Initial runs reported 

![Image](https://github.com/user-attachments/assets/43b54c44-719a-433d-8668-e83c1438a647)
the same tests showing up as a duplicates (not merged with CI extension) in the same run, increasing the total test amount

while the same tests fail, it will consistently appear like this

Example #2:
Here only the test which was showing up with duplicates every time is the only test enabled
![Image](https://github.com/user-attachments/assets/76ef6094-0430-4d12-bdd5-d9ba090a3130)

![Image](https://github.com/user-attachments/assets/d3ff748e-3c21-4845-8e89-2f438d2588c3)
Example #3:

![Image](https://github.com/user-attachments/assets/35b138de-2745-42a9-80b8-ba83d5af641c)
When less tests were failing i got a test for which only the reruns appeared on report portal 
(the one with 2 failed is only showing the retries, according to the time in pipeline logs)
![Image](https://github.com/user-attachments/assets/90543971-ef7e-4e3f-8632-2956f9a07e14)
